on: workflow_dispatch

jobs:
  scanaction:
    runs-on: ubuntu-latest
    steps:
      - uses: danta-org/scan-stats@v3
        with:
          githubtoken: ${{ secrets.ORG_ADMIN_ACCESS_TOKEN }}
          org: symplr-sandbox
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
      - uses: actions/upload-artifact@v3
        with:
          name: security-alerts
          path: ./
