on: workflow_dispatch

jobs:
  scanaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: danta-org/scan-stats@v3
        with:
          githubtoken: ${{ secrets.ORG_ADMIN_ACCESS_TOKEN }}
          org: symplr-sandbox
      - name: Commit files
        run: |
          git config --local user.email "dta@symplr.com"
          git config --local user.name "GitHub Action"
          git add code-scan.json
          git add secret-scan.json
          git commit -m "Add changes" -a
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - uses: actions/upload-artifact@v3
        with:
          name: security-alerts
          path: ./
