on: workflow_dispatch

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const result = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            console.log(result)
            let data = JSON.stringify(result, null, 2);
            fs.writeFileSync('repoinfo.json', data);
      - uses: actions/upload-artifact@v3
        with:
          name: repo-info
          path: repoinfo.json
