on: workflow_dispatch

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            console.log(result)
