on: workflow_dispatch

jobs:
  getalerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_ADMIN_ACCESS_TOKEN }}
          script: |
            const fs = require('fs');
            
            const codeScanningResult = github.rest.secretScanning.listAlertsForOrg.endpoint.merge({
              org: "symplr-sandbox",
            })
            const codeScanningAlerts = await github.paginate(codeScanningResult)
            let codeScanningData = JSON.stringify(codeScanningAlerts, null, 2);
            fs.writeFileSync('artifacts/code-scan-alerts.json', codeScanningData);
      - uses: actions/upload-artifact@v3
        with:
          name: security-alerts
          path: artifacts/
