on: workflow_dispatch

jobs:
  getalerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_ADMIN_ACCESS_TOKEN }}
          script: |
            const query =
              `query ($org: String! $repo: String! $cursor: String){
              repository(owner: $org name: $repo) {
                name
                dependencyGraphManifests(first: 100 after: $cursor) {
                pageInfo {
                  hasNextPage
                  endCursor
                }

                nodes {
                  dependenciesCount
                  filename
                  dependencies {
                  nodes {
                    packageManager
                    packageName
                    requirements
                    hasDependencies
                    repository {
                      name
                      owner {
                        login
                      }
                      licenseInfo {
                        name
                        spdxId
                        url
                      }
                    }
                  }
                  }
                }
                }
              }
            }`;
            
            const variables = {
              owner: 'symplr-sandbox',
              name: 'wfm-shs-application-test-scanning',
              cursor: 'pagination'
            }
            getDepsResult = await github.graphql(query, variables)
            console.log(getDepsResult)

