on: workflow_dispatch

jobs:
  getalerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_ADMIN_ACCESS_TOKEN }}
          script: |
            const fs = require('fs');
            const result = github.rest.codeScanning.listAlertsForRepo({
              owner: "symplr-sandbox",
              repo: "wfm-shs-application-test-scanning"
            })
            
            const alerts = await github.paginate(result)
            console.log(alerts)
        
        #let data = JSON.stringify(result, null, 2);
        #fs.writeFileSync('repoinfo.json', data);
      
      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: repo-info
      #    path: repoinfo.json
