on: workflow_dispatch

jobs:
  getalerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_ADMIN_ACCESS_TOKEN }}
          script: |
            const query =
              `query ($org: String! $repo: String!){
              repository(owner: $org name: $repo) {
                name
                vulnerabilityAlerts(first: 100) {
                  nodes {
                    createdAt
                    dismissedAt
                    securityVulnerability {
                      package {
                        name
                      }
                      advisory {
                        description
                      }
                    }
                  }
                }
                      }
                    }`;
            
            const variables = {
              owner: 'symplr-sandbox',
              name: 'wfm-shs-application-test-scanning',
              cursor: 'pagination'
            }
            getDepsResult = await github.graphql(query, variables)
            console.log(getDepsResult)

