on: workflow_dispatch

jobs:
  getalerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_ADMIN_ACCESS_TOKEN }}
          script: |
            const query =
              `query ($org: String! $repo: String!){
              repository(owner: $org name: $repo) {
                name
                vulnerabilityAlerts {
                  totalCount
                  nodes {
                    createdAt
                    dismissedAt
                    securityVulnerability {
                      package {
                        name
                      }
                      advisory {
                        description
                      }
                    }
                  }
                  pageInfo {
                    endCursor
                    hasNextPage
                  }
                }
                      }
                    }`;
            
            const variables = {
              org: "symplr-sandbox",
              repo: "wfm-shs-application-test-scanning"
            }
            const getDepsResult = await github.graphql(query, variables)
            console.log(getDepsResult.repository.vulnerabilityAlerts.pageInfo.hasNextPage)

